---
jobs:
  - name: build-image
    plan:
      - get: repo
        trigger: true
      - put: build-status
        params: { state: pending, commit: repo }
      - task: build
        file: repo/ci/build-task.yaml
        privileged: true
        on_failure: &on_failure
          put: build-status
          params: { state: failure, commit: repo }
      - put: barth-tech-registry
        params:
          image: image/image.tar
        on_failure: *on_failure
  - name: test
    plan:
      - get: barth-tech-registry
        passed: [build-image]
        trigger: true
      - get: repo
        passed: [build-image]
      - task: unit-tests
        image: barth-tech-registry
        config:
          platform: linux
          resouce_image: {repository: dummy}
          run:
            path: /usr/local/bin/pytest
            args: [/src/tests]
        on_failure: *on_failure
      - put: build-status
        params: { state: success, commit: repo }


resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/r-bar/concourse-github-status.git
      branch: master
    webhook_token: ((webhook-token))
    check_every: 24h

  - name: build-status
    type: github-status
    source:
      owner: r-bar
      repository: concourse-github-status
      access_token: ((github-access-token))

  - name: barth-tech-registry
    type: registry-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      username: ((registry.username))
      password: ((registry.password))


resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      tag: latest
