---
jobs:
  - name: build-image
    plan:
      - get: repo
        trigger: true
      - put: build-status
        params: { state: pending, commit: repo }
      - task: test
        on_failure: &on_failure
          put: build-status
          params: { state: failure, commit: repo }
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: 3.8-alpine
          inputs: [{name: repo}]
          run:
            path: /bin/ash
            args:
              - -c
              - "cd repo && pip install .[dev] && pytest"
      - put: barth-tech-registry
        params:
          build: repo
        on_failure: *on_failure

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/r-bar/concourse-github-status.git
      branch: master
    webhook_token: ((webhook-token))
    check_every: 24h

  - name: build-status
    type: github-status
    source:
      owner: r-bar
      repository: concourse-github-status
      access_token: ((github-access-token))

  - name: barth-tech-registry
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      username: ((registry.username))
      password: ((registry.password))


resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      tag: latest
